### ISSUE TITLE
Failed to search in amtrak

### ISSUE THREAD

**Issue by bs3265** [nikhilweee/amtrak-telegram-bot#1]
hi @nikhilweee, great idea and nice work. I am trying to set it up but facing some issue when the bot run the search. 
```
search.py.log_status:42 | 201 https://www.amtrak.com/-63Vp47M2/ezg/JJORcQ/3JE7LJVJ/WV47agRFFAY/VnpL/NSgvYD0B success: Error
search.py.log_status:42 | 201 https://www.amtrak.com/-63Vp47M2/ezg/JJORcQ/3JE7LJVJ/WV47agRFFAY/VnpL/NSgvYD0B success: Error
search.py.log_status:42 | 200 https://www.amtrak.com/v4/journey-solution-option success: Error
```
Here is the error message I got when the search ran.  (ex: when I do `/best 1` or `/sub` to a new job)

One more question I have is about the ATB_SENSOR_DATA value. is this only needs the sensor_data value or the whole JSON object?  Here is my sample value: 
```
ATB_SENSOR_DATA={"sensor_data":"XXXX"}
```

Thanks

**Comment by nikhilweee** [comment]
`ATB_SENSOR_DATA` should be a string, not a dict. Can you try enclosing it in quotes and try again? 
```
ATB_SENSOR_DATA='{"sensor_data":"XXXX"}'
```

**Comment by bs3265** [comment]
Thank you for the information. I did the change but looks like it now shows a different message. 

```
An error occurred while processing your request.
An error occured while searching Amtrak.
```
or 
```
An error occured while searching Amtrak.
Request timed out. Please try again later.
```

is there a time limit set for the amtrak call? maybe we can increase that limit.

**Comment by bs3265** [comment]
I think I got it working now. thank you for your help.
